monitor=,preffered,auto,1.6

# Move focus with mainMod + arrow keys
unbind = SUPER, H
unbind = SUPER, L
unbind = SUPER, K
unbind = SUPER, J
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d
# rebind to select ALL
unbind = SUPER, A
bindd = SUPER, A, Universal select all, sendshortcut, CTRL, A, activewindow

bindd = SUPER, Q, Toggle window split, togglesplit
